CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID  INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL    VARCHAR(255) NOT NULL,
    LOGIN    VARCHAR(255) NOT NULL,
    NAME     VARCHAR(255) NOT NULL,
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS MPA_RATINGS
(
    RATING_ID INT PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID      INT PRIMARY KEY AUTO_INCREMENT,
    NAME         VARCHAR(255) NOT NULL,
    DESCRIPTION  TEXT         NOT NULL,
    RELEASE_DATE DATE,
    DURATION     INT,
    MPA_RATING   INT REFERENCES MPA_RATINGS (RATING_ID)
);


CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_ID INT PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    GENRE_ID INT NOT NULL,
    FILM_ID  INT NOT NULL,
    CONSTRAINT film_genres_pk PRIMARY KEY (GENRE_ID, FILM_ID),
    CONSTRAINT film_genres_fk FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (GENRE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIKES
(
    FILM_ID INT REFERENCES FILMS (FILM_ID),
    USER_ID INT REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_FRIENDS
(
    USER_ID           INT REFERENCES USERS (USER_ID),
    FRIEND_ID         INT REFERENCES USERS (USER_ID),
    FRIENDSHIP_STATUS BOOLEAN
);